background {
    monitor =
    path = /home/thoren/Wallpapers/Black.jpeg
    color = rgba(0, 0, 0, 1.0)
    blur_passes = 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}

label {
monitor = eDP-1
text = $TIME12
color = rgb(c3c3c3)
font_size = 96
font_family = SF Pro Display
position = 32, 0
halign = left
valign = bottom
}

auth{
fingerprint:enabled = true
}
